services:
  server:
    build:
      context: .
    volumes:
      - "./.ssl/ssl_cert.pem:/build/.ssl/ssl_cert.pem"
      - "./.ssl/ssl_key.pem:/build/.ssl/ssl_key.pem"
networks:
  static-network:
    ipam:
      config:
        - subnet: 195.133.32.0/16
          ip_range: 195.133.46.214/24
